### ISSUE TITLE
Wafflestudio VPC private-subnet-b 생성

### ISSUE THREAD

**Issue by chosanglyul** [wafflestudio/waffle-account-server#28]
내부 NLB는 2개 이상의 private-subnet을 요구되므로, private-subnet-b를 생성하여 NLB 세팅을 완료한다.

**Comment by davin111** [comment]
이거는 실제 진행할 때 같이 얘기해보면 좋을 거 같습니다.

**Comment by davin111** [comment]
K8S 적용으로 자연스레 해소됨. cluster node 가 이미 여러 az 에 분산되어 있음.
